apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: {{ .Values.ingressPath }}
        pathType: Prefix
        backend:
          service:
            name:  {{ .Chart.Name }}
            port:
              number: 80
      - path: {{ .Values.ingressPath2 }}
        pathType: Prefix
        backend:
          service:
            name:  {{ .Chart.Name }}
            port:
              number: 80
      - path: {{ .Values.ingressPath3 }}
        pathType: Prefix
        backend:
          service:
            name:  {{ .Chart.Name }}
            port:
              number: 80
      - path: {{ .Values.ingressPath4 }}
        pathType: Prefix
        backend:
          service:
            name:  {{ .Chart.Name }}
            port:
              number: 80
      - path: {{ .Values.ingressPath5 }}
        pathType: Prefix
        backend:
          service:
            name:  {{ .Chart.Name }}
            port:
              number: 80
