kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            app: {{ .Values.ingressController }}
