apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "pdb-{{ .Chart.Name }}"
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}